### ISSUE TITLE
Re-tag version "1.1.2" to "v1.2" or "v1.1.2"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-authenticating-secgroup#12]
Terraform Registry reads the "vXX" tags for release versions.

@phuonghuynh can you help re-tag the "1.1.2" tag to either "v1.2" or "v1.1.2"? Thanks!

**Comment by phuonghuynh** [comment]
Yes

**Comment by phuonghuynh** [comment]
Fixed https://github.com/riboseinc/terraform-aws-authenticating-secgroup/releases/tag/v1.1.2
