### ISSUE TITLE
Use AWS STS to utilize temporary tokens

### ISSUE THREAD

**Issue by phuonghuynh** [riboseinc/terraform-aws-authenticating-secgroup#14]
Ref riboseinc/aws-authenticating-secgroup-scripts/issues/4

**Comment by phuonghuynh** [comment]
STS is used as the same way we would use long-term credentials to sign a request. I thinks this issue could be closed.

**Comment by ronaldtse** [comment]
I originally meant that the client script used for authentication should automatically generate a new STS token to authenticate with Lambda. Perhaps we move this issue to the other repo?

**Comment by phuonghuynh** [comment]
Yep, moved to riboseinc/aws-authenticating-secgroup-scripts/issues/10

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh !
