### ISSUE TITLE
Shell script that authenticates against this API gateway using an AWS access key and secret key

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-authenticating-secgroup#2]
Given now we have the dynamic secgroup, we also need a shell script that can generate the AWS v4 signature to authenticate against the API gateway.

@phuonghuynh could you help with this? Thanks!

**Comment by phuonghuynh** [comment]
@erikbor I using Postman to test the AWS API. Postman can help to auto-generate Signature v4. You can use my export Postman enclosed while i write the bash script. I using last Postman version.

You can see more info how Postman support AWS Signature here, https://www.getpostman.com/docs/postman/sending_api_requests/authorization


[terraform-dyna-sec.postman_collection.json.zip](https://github.com/riboseinc/terraform-aws-authenticating-secgroup/files/1554762/terraform-dyna-sec.postman_collection.json.zip)

**Comment by ronaldtse** [comment]
@phuonghuynh actually we need some command-line tool for the authentication. Could you help with this? Thanks!

**Comment by phuonghuynh** [comment]
Yes @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh !

**Comment by phuonghuynh** [comment]
Shell script to use with this API can be check out [here](https://github.com/phuonghuynh/aws-authenticating-secgroup-scripts)
