### ISSUE TITLE
InvalidParameterValue: Invalid region: []

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-authenticating-secgroup#23]
Hi @phuonghuynh,

I have the following in a terraform setup:

```
module "dynamic-secgroup-global-vpn" {
  source = "github.com/riboseinc/terraform-aws-authenticating-secgroup"

  # prefix string used in named resources
  name = "auth-"

  description = "vpn-dyn-access"

  # Time to expiry for every rule.
  # Default: 600 seconds.
  time_to_expire = 600

  security_groups = [
	{
		"group_ids" = [
			"${aws_security_group.vpn-dyn.id}"
		],
		"rules" = [
			{
				"type" = "ingress",
				"from_port" = "${var.ports["ssh"]}",
				"to_port" = "${var.ports["ssh"]}",
				"protocol" = "tcp"
			}
		],
		"region_name" = "us-west-2"
	}
  ]
}
```

When I run `terraform plan` it fails with:

```
Error: Error refreshing state: 2 error(s) occurred:

* module.global.module.dynamic-secgroup-global-vpn.module.gateway_revoke.data.aws_region.current: 1 error(s) occurred:

* module.global.module.dynamic-secgroup-global-vpn.module.gateway_revoke.data.aws_region.current: data.aws_region.current: InvalidParameterValue: Invalid region: []
	status code: 400, request id: 77acf0ed-8b62-4e88-8d3c-635158b04e6e
* module.global.module.dynamic-secgroup-global-vpn.module.gateway_authorize.data.aws_region.current: 1 error(s) occurred:

* module.global.module.dynamic-secgroup-global-vpn.module.gateway_authorize.data.aws_region.current: data.aws_region.current: InvalidParameterValue: Invalid region: []
	status code: 400, request id: 14e7c644-42b8-4081-a1dc-0a3ecd6ce4f7
```

Can you verify that `"region_name"` is correct, and do you have any pointers which could have caused this? Cheers

**Comment by phuonghuynh** [comment]
@erikbor
The error is about missing region_name where the API should deployed to.
The module example using provider as bellow
```
provider "aws" {
  region  = "us-west-2"
}
```

**Comment by ronaldtse** [comment]
@phuonghuynh do you mean that we need to pass in provider into the module? The error that @erikbor pointed out is exactly the error, it seems more like that the "`region_name`" didn't get passed to the "`data.aws_region.current`"?

**Comment by phuonghuynh** [comment]
Yes, @ronaldtse 
We need to pass provider used to deploy the API, https://www.terraform.io/docs/providers/aws/
The example using credentials in "~/.aws" and "region_name" need to pass in provider

**Comment by ronaldtse** [comment]
I see, can you copy/edit the above example to see how to pass in the provider, eg is it just called “aws” or something like “aws.xyz”?

**Comment by phuonghuynh** [comment]
Yes, updated the readme to include sample provider, https://github.com/riboseinc/terraform-aws-authenticating-secgroup/blob/master/README.md

**Comment by ronaldtse** [comment]
I saw the update, but surely you meant to pass the outside provider to inside the module? Because in Terraform 0.11+ he provider scope outside is not passed into the module provider scope.

**Comment by phuonghuynh** [comment]
The provider can be configured using inside credentials read from variables, i will update the example to demonstrate it ^

**Comment by ronaldtse** [comment]
We really don’t want the module to read credentials — can’t we just use the normal Terraform way of passing providers? Then we don’t need to pass the region name?

**Comment by phuonghuynh** [comment]
@ronaldtse we can config provider as bellow, this way (previous version used this way) Terraform not read credentials in "~/.aws". Is it ok?

```
variable "aws_account_id" {
  description = "AWS account id"
}

variable "aws_access_key" {
  description = "AWS access key"
}

variable "aws_secret_key" {
  description = "AWS secret key"
}

variable "aws_region" {
  description = "AWS region"
  default     = "us-west-2"
}

# where should this API deployed to
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "${var.aws_region}"
}

```

**Comment by ronaldtse** [comment]
@phuonghuynh I was talking about this kind of syntax?

```hcl
provider "aws" {
  alias  = "usw1"
  region = "us-west-1"
}

provider "aws" {
  alias  = "usw2"
  region = "us-west-2"
}

module "tunnel" {
  source    = "./tunnel"
  providers = {
    "aws.src" = "aws.usw1"
    "aws.dst" = "aws.usw2"
  }
}
```

**Comment by phuonghuynh** [comment]
In that syntax, the providers will read "~/.aws" since we not providing "credentials" to let Terraform do apply action

> in Terraform 0.11+ he provider scope outside is not passed into the module provider scope.

Our module not configure its provider, it using provider provided outside. This way, user can config their own provider. Terraform v0.11+ support 4 type of providers:
- Static credentials
- Environment variables
- Shared credentials file
- EC2 Role

> Then we don’t need to pass the region name?

If we dont want to pass region name, then we can use "Environment variables" provider type.

The sample in https://github.com/riboseinc/terraform-aws-authenticating-secgroup/issues/23#issuecomment-373891853 is "Static credentials" provider.

An other option is that provider can use "Assume role" but i will need to figure out how it work, https://www.terraform.io/docs/providers/aws/#assume-role

**Comment by phuonghuynh** [comment]
I think this sample is good, i borrowed from https://github.com/riboseinc/terraform-aws-codecommit-sqs


```
variable "aws-region" {
  default = "my-aws-region"
}

provider "aws" {
  region = "${var.aws-region}"
  alias = "default"
}

module "dynamic-secgroup" {
  providers = {
    aws = "aws.default"
  }
  ...
}
...
```


However, the terraform v0.11+ keep asking for "region-name" always. I think this is a terraform bug, related issue, https://github.com/terraform-providers/terraform-provider-aws/issues/1043

**Comment by phuonghuynh** [comment]
@ronaldtse are we good at provider config? i think the module should not configure provider, let user do it. User can pass provider to the module to deploy it.

**Comment by ronaldtse** [comment]
@phuonghuynh yes you're right, user should pass provider. I'm waiting for @erikbor 's results.

**Comment by ronaldtse** [comment]
Confirmed working. Thanks @phuonghuynh !
