### ISSUE TITLE
use prefix for CloudWatch Log group name

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-authenticating-secgroup#28]
Hi @phuonghuynh,

Can you implement the usage of the prefix for CloudWatch Log group names please?
Currently these `API-Gateway-Execution-Logs_carabxgux2/dev` groups are created which make it difficult for us to check which ones belong to which environment.

E.g.: `API-Gateway-Execution-Logs-testenv-carabxgux2/dev` would work for us (`testenv` is the prefix).

Thanks!

**Comment by ronaldtse** [comment]
@phuonghuynh is this fixed? If so could we close this? Thanks!

**Comment by phuonghuynh** [comment]
Yes, it should be closed
