### ISSUE TITLE
Add JSON s3 bucket support to this module

### ISSUE THREAD

**Issue by erikbor** [riboseinc/terraform-aws-authenticating-secgroup#31]
Hi @phuonghuynh,

Can you modify this module to include the JSON s3 authentication logic.

So currently we have an IAM group that is attached to the `aws_iam_policy_document` that allows `execute-api:Invoke`.

This should be kept, so users in that IAM group can POST to the API endpoint, but we like to have the JSON s3 authentication logic too so we only allow users that are in the JSON to have their IPs added to the security group.

The reason for this request is that there are significant delays with IAM replication between availability zones and regions (see: (https://github.com/riboseinc/terraform-aws-iam-authenticating-group/issues/32). So we can't just rely on IAM groups for the "authentication" of this module.

**Comment by phuonghuynh** [comment]
> so users in that IAM group can POST to the API endpoint

so users in "iam-group" need to grant access to the API endpoint, doesn't it? This  module should not maintain this operation.

**Comment by phuonghuynh** [comment]
@erikbor do you have any sample for the json post to S3? Atm, the "security_groups" is as bellow

```
[
  {
    "group_ids": [
      "sg-c9c72eb5"
    ],
    "rules": [
      {
        "type": "ingress",
        "from_port": 55,
        "to_port": 55,
        "protocol": "tcp"
      }
    ],
    "region_name": "us-west-2"
  }
]

```

**Comment by ronaldtse** [comment]
@phuonghuynh this JSON looks fine. The key point is we want authentication to use a JSON file on S3 rather than using the IAM group, since the IAM group responds slowly.

**Comment by ronaldtse** [comment]
@phuonghuynh I misunderstood your question. So basically, users that can authenticate against this dynamic-secgroup is stored in a list on S3 in JSON format. These users are already allowed to access the Lambda function provided by this module. The module will need to check if the particular user is provided in the JSON file stored in S3, if yes, then it opens up the security group; otherwise, it returns 403.

**Comment by phuonghuynh** [comment]
@erikbor @ronaldtse so 

> These users are already allowed to access the Lambda function provided by this module

These users dont need to access Lambda, but need to be granted to access API

> The module will need to check if the particular user is provided in the JSON file stored in S3

Lambda check the User who calling API that existing in the JSON; if YES, then opens up the Security Group, otherwise, it returns 403.

Is this correct?

**Comment by ronaldtse** [comment]
> These users dont need to access Lambda, but need to be granted to access API

Yes.

> Lambda check the User who calling API that existing in the JSON; if YES, then opens up the Security Group, otherwise, it returns 403.

Yes.

Thanks!
